import { v4 as uuidv4 } from "uuid";
import type { Lead } from "../types";
import { addDays, subDays, format } from "date-fns";

const today = new Date();

export function createSeedData(): Lead[] {
  return [
    {
      id: uuidv4(),
      name: "נועה כהן",
      phone: "0541234567",
      service: "איפור כלה",
      stage: "booked",
      source: "instagram",
      appointmentDate: format(addDays(today, 5), "yyyy-MM-dd"),
      notes: "חתונה בגן אירועים ״הגינה הסודית״. רוצה לוק טבעי וזוהר",
      history: [
        {
          id: uuidv4(),
          date: format(subDays(today, 60), "yyyy-MM-dd"),
          service: "איפור",
          amount: 350,
          notes: "אירוע משפחתי — איפור ערב",
        },
      ],
      createdAt: subDays(today, 14).toISOString(),
      updatedAt: subDays(today, 2).toISOString(),
    },
    {
      id: uuidv4(),
      name: "מיכל לוי",
      phone: "0529876543",
      service: "צביעה",
      stage: "new",
      source: "whatsapp",
      notes: "שלחה תמונות השראה, רוצה בלונד חם",
      history: [],
      createdAt: subDays(today, 1).toISOString(),
      updatedAt: subDays(today, 1).toISOString(),
    },
    {
      id: uuidv4(),
      name: "שירן אברהם",
      phone: "0507654321",
      service: "תסרוקת",
      stage: "quoted",
      source: "referral",
      referredBy: "נועה כהן",
      appointmentDate: format(addDays(today, 3), "yyyy-MM-dd"),
      notes: "תסרוקת לאירוע — שיער ארוך ומתולתל",
      history: [],
      createdAt: subDays(today, 5).toISOString(),
      updatedAt: subDays(today, 3).toISOString(),
    },
    {
      id: uuidv4(),
      name: "דנה ישראלי",
      phone: "0538765432",
      service: "טיפול שיער",
      stage: "done",
      source: "returning",
      amountPaid: 280,
      history: [
        {
          id: uuidv4(),
          date: format(subDays(today, 30), "yyyy-MM-dd"),
          service: "טיפול שיער",
          amount: 280,
          notes: "טיפול קראטין",
        },
        {
          id: uuidv4(),
          date: format(subDays(today, 90), "yyyy-MM-dd"),
          service: "צביעה",
          amount: 450,
          notes: "צביעה + תסרוקת",
        },
      ],
      createdAt: subDays(today, 45).toISOString(),
      updatedAt: subDays(today, 7).toISOString(),
    },
    {
      id: uuidv4(),
      name: "יעל מזרחי",
      phone: "0502345678",
      service: "הארכות",
      stage: "followup",
      source: "instagram",
      followUpDate: format(today, "yyyy-MM-dd"),
      notes: "התעניינה בהארכות, ביקשה לחזור אליה בעוד שבוע",
      history: [],
      createdAt: subDays(today, 10).toISOString(),
      updatedAt: subDays(today, 3).toISOString(),
    },
    {
      id: uuidv4(),
      name: "רונית פרץ",
      phone: "0545678901",
      service: "איפור",
      stage: "new",
      source: "whatsapp",
      appointmentDate: format(addDays(today, 1), "yyyy-MM-dd"),
      notes: "איפור ליומולדת, רוצה משהו דרמטי",
      history: [],
      createdAt: today.toISOString(),
      updatedAt: today.toISOString(),
    },
    {
      id: uuidv4(),
      name: "אורלי גולדשטיין",
      phone: "0521112233",
      service: "תסרוקת",
      stage: "booked",
      source: "referral",
      referredBy: "דנה ישראלי",
      appointmentDate: format(addDays(today, 7), "yyyy-MM-dd"),
      notes: "תסרוקת לחתונה של חברה",
      history: [
        {
          id: uuidv4(),
          date: format(subDays(today, 120), "yyyy-MM-dd"),
          service: "תסרוקת",
          amount: 300,
        },
      ],
      createdAt: subDays(today, 20).toISOString(),
      updatedAt: subDays(today, 1).toISOString(),
    },
    {
      id: uuidv4(),
      name: "טלי בן דוד",
      phone: "0533445566",
      service: "צביעה",
      stage: "quoted",
      source: "returning",
      notes: "רוצה לשנות צבע — מחום לקר. ביקשה הצעת מחיר",
      history: [
        {
          id: uuidv4(),
          date: format(subDays(today, 45), "yyyy-MM-dd"),
          service: "צביעה",
          amount: 400,
          notes: "גוונים חמים",
        },
      ],
      createdAt: subDays(today, 3).toISOString(),
      updatedAt: subDays(today, 1).toISOString(),
    },
  ];
}
